theme: jekyll-theme-slate
title: AZ-801 - Training - Configuring Windows Server Hybrid Advanced Services
description: Companion material and resources for the course 'Configuring Windows Server Hybrid Advanced Services' delivery by Ricardo Cabral. 
relative_links:
  enabled: true
  collections: true
exclude:
  - .github/
include:
  - README.md
author: Ricardo Cabral
twitter_username: rramoscabral
github_username:  rramoscabral
